repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        enable: disable  # Ensure this hook is enabled to fix trailing whitespace
      - id: end-of-file-fixer
        enable: disable  # Ensure this hook is enabled to fix final newlines
      - id: check-yaml  # Keep this for YAML checks

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: ["--disable=C0114", "--disable=C0301", "--disable=W0105", "--disable=E0611", "--disable=C0411", "--disable=W0621", "--disable=E0401", "--disable=E0015", "--disable=E0012"]
