- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.15.0
  hooks:
    - id: pylint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
      disable: true  # This disables the trailing-whitespace hook
    - id: end-of-file-fixer
      disable: true  # This disables the end-of-file-fixer hook
