repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        enable: false  # Disable trailing-whitespace hook
      - id: end-of-file-fixer
        enable: false  # Disable end-of-file-fixer hook
      - id: check-yaml
        enable: true   # Keep this hook enabled, or disable it if you wish

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        enable: false  # Disable pylint hook completely
