name: CI Pipeline

on: [push, pull_request]  # Trigger on push and pull request events

jobs:
  # Linting Job (Pre-commit + Pylint)
  lint:
    runs-on: ubuntu-latest  # You can switch to `ubuntu-latest` for more flexibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask keras numpy Pillow pytest tensorflow==2.13.0 pylint pre-commit  # Install pylint and pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files  # Ensure pre-commit hooks run on all files

      - name: Run pylint
        run: pylint .  # Run pylint on the entire codebase (or specify a directory)

  # Unit Tests Job (including Happy/Sad Path tests)
  test:
    runs-on: ubuntu-latest  # Running tests on Ubuntu
    needs: lint  # Run this job only after linting passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask keras numpy Pillow pytest tensorflow==2.13.0  # Install testing dependencies

      - name: Run unit tests
        run: pytest tests_main.py  # Ensure this points to your unit tests

      - name: Run happy and sad path tests
        run: pytest -k "test_prediction" tests_main.py  # You can filter for Happy/Sad Path tests using `-k` to specify test names

  # Acceptance Tests Job
  acceptance_tests:
    runs-on: ubuntu-latest  # Run on the latest version of Ubuntu
    needs: [test]  # This ensures acceptance tests only run if the unit and happy/sad path tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask keras numpy Pillow pytest tensorflow==2.13.0  # Install testing dependencies

      - name: Run acceptance tests
        run: pytest -k "test_acceptance" tests_main.py  # Run the acceptance tests by filtering for acceptance tests with `-k`